apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: demojam-gateway-i7vc
  namespace: phayes1-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:63dc08e0903b0c8f510af06a27e97dc1289e08dd2ae9ef6aa1a65d465b726988
        name: my-nodejs
        resources: {}
status: {}
