apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: demojam-gateway-i7vc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: demojam-gateway-i7vc
    app.kubernetes.io/part-of: demojam
  name: demojam-gateway-i7vc
  namespace: phayes1-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: demojam-gateway-i7vc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: demojam-gateway-i7vc
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload:FgnBp-demojam-gateway-i7vc
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
