apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: demojam-gateway-i7vc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: demojam-gateway-i7vc
    app.kubernetes.io/part-of: demojam
  name: demojam-gateway-i7vc
  namespace: phayes1-tenant
spec:
  path: /
  port:
    targetPort: 3001
  to:
    kind: Service
    name: demojam-gateway-i7vc
    weight: null
status: {}
